
name: Deploy and Publish

on:
  push:
    branches:
      - main

jobs:

  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Install dependencies
        run: npm ci
      
      - name: Commit, release version and publish on NPM
        run: |
          git config --global user.email "igortrindademe@gmail.com"
          git config --global user.name "Igor Trindade"
          npm run release --commit-all
          git push --follow-tags origin main
          npm publish --tolerate-republish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}